// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxtl1eDo6Eoi0O5FVmAY_BkwhSn35RY-Y',
    appId: '1:417522651418:web:93f96c0f4eacab6af31ca3',
    messagingSenderId: '417522651418',
    projectId: 'restaurant-app-d3cbf',
    authDomain: 'restaurant-app-d3cbf.firebaseapp.com',
    storageBucket: 'restaurant-app-d3cbf.firebasestorage.app',
    measurementId: 'G-ECK8DMSKXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNVaOF3rGv6CJae8sr_GpR_6oW1SKeCls',
    appId: '1:417522651418:android:e5738b60247f4a14f31ca3',
    messagingSenderId: '417522651418',
    projectId: 'restaurant-app-d3cbf',
    storageBucket: 'restaurant-app-d3cbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9XVzl0F6ACmxiPtWeLEgLHklw-O8ahDs',
    appId: '1:417522651418:ios:0b30f59c0839d7f9f31ca3',
    messagingSenderId: '417522651418',
    projectId: 'restaurant-app-d3cbf',
    storageBucket: 'restaurant-app-d3cbf.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9XVzl0F6ACmxiPtWeLEgLHklw-O8ahDs',
    appId: '1:417522651418:ios:0b30f59c0839d7f9f31ca3',
    messagingSenderId: '417522651418',
    projectId: 'restaurant-app-d3cbf',
    storageBucket: 'restaurant-app-d3cbf.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxtl1eDo6Eoi0O5FVmAY_BkwhSn35RY-Y',
    appId: '1:417522651418:web:e5df7c8818a29af2f31ca3',
    messagingSenderId: '417522651418',
    projectId: 'restaurant-app-d3cbf',
    authDomain: 'restaurant-app-d3cbf.firebaseapp.com',
    storageBucket: 'restaurant-app-d3cbf.firebasestorage.app',
    measurementId: 'G-JQ5PBYNZYZ',
  );
}
